services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./letsencrypt/data:/data
      - ./letsencrypt/etc:/etc/letsencrypt
    mem_limit: 250m
    cpus: 0.15
  odoo:
    image: odoo:13.0
    restart: unless-stopped
    platform: linux/x86_64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/etc:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
    command: >
      odoo
      --dev all
      -r odoo
      -w odoo_password
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --log-level=debug 
      --max-cron-threads=1 

  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    mem_limit: 250m
    cpus: 0.15

volumes:
  odoo-web-data: