services:
  odoo:
    image: odoo:13.0
    restart: unless-stopped
    platform: linux/x86_64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-dev-data:/var/lib/odoo
      - ./odoo/etc:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
    command: >
      odoo
      --dev all
      -r odoo
      -w odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --log-level=debug
      --max-cron-threads=1

  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

volumes:
  odoo-dev-data:
  postgres-dev-data:
